[package]
name = "art"
version = "0.1.0"
authors = ["muthu95 <muthugaja1410@gmail.com>"]
edition = "2018"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
rustc-test = "*"
rand = "0.7"
debugit = "*"
